name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # run manually
    inputs:
      platforms:
        description: OS/arch targets to build for (comma-separated list)
        default: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # we need tags for docker version tagging
        fetch-tags: true
        fetch-depth: 0
    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      run: docker buildx build --progress=plain --platform ${{ github.event.inputs.platforms }} -f Dockerfile -t test .
